// <auto-generated />
namespace IFES.POO2.Ipharm.AcessoDados.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MigracaoInicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MigracaoInicial));
        
        string IMigrationMetadata.Id
        {
            get { return "201805220034410_MigracaoInicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
