// <auto-generated />
namespace IFES.POO2.Ipharm.AcessoDados.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class M : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M));
        
        string IMigrationMetadata.Id
        {
            get { return "201806040035203_M"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
